# Generated by Django 5.0.1 on 2024-01-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=45)),
                ('checkout_date', models.CharField(max_length=45)),
                ('return_date', models.TextField()),
                ('book_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=45)),
                ('checkout_date', models.CharField(max_length=45)),
                ('returned_date', models.TextField()),
                ('title', models.IntegerField()),
                ('author', models.IntegerField()),
                ('description', models.CharField(max_length=45)),
                ('img', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('question', models.TextField()),
                ('admin_email', models.CharField(max_length=45)),
                ('response', models.TextField()),
                ('closed', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('book_id', models.BigIntegerField()),
                ('review_description', models.TextField()),
            ],
        ),
    ]
